### ISSUE TITLE
website doesnt run locally

### ISSUE THREAD

**Issue by sw-yx** [doczjs/docz-website#44] opened 2019-01-29 21:57 UTC
i'm getting this based on just doing `yarn dev` on the current master:

```bash

This dependency was not found:

* null in ./.docz/app/root.jsx

To install it, you can run: npm install --save null

```

that file has this weird code:

```js
import Wrapper from 'null'

const Root = () => <Theme hashRouter={undefined} wrapper={Wrapper} />

export default hot(module)(Root)
```

after i install the `null` package:

![image](https://user-images.githubusercontent.com/6764957/51943218-08816680-23bd-11e9-9326-eeb6a927d28f.png)

not sure what is going on but just sharing

**Comment by dism34** [comment] 2019-02-27 15:45
Same problem

**Comment by macklinu** [comment] 2019-03-25 22:21
Unable to reproduce after cloning the repo (on commit 53feacb49dd6c4ceb2c8b98385627fb4a9981d35) and running:

* `yarn`
* `yarn dev`

**Comment by sw-yx** [comment] 2019-03-27 20:04
heads up that ongoing dev is at https://github.com/pedronauck/docz-website/tree/v1 (im not involved.. yet)

**Comment by rakannimer** [comment] 2019-10-07 13:57
Hey 

Thanks for reporting this issue. I couldn't reproduce with the latest version of the repo at 97bdc7fc594a7913c6b89c5bc543f8e7c9f70ea2

Closing this as I'm assuming it's related to previous versions of docz-website, please feel free to re-open if it happens to you again.

**Closed by rakannimer** 2019-10-07 13:57 UTC
